In [1]:
%load_ext autoreload

%autoreload 2

In [8]:
from Core import Nanoparticle as NP


p = NP.Nanoparticle()

p.truncated_octahedron(6,1,{'Pt' : 1})
p.atoms.symbols[10]

Resulting stoichiometry: {'Pt': 140}


'Pt'

In [13]:
import sys
sys.path.append('/home/riccardo/Projects/NanoParticleLibrary/')

In [39]:
from Core import Nanoparticle as NP
import numpy as np
p = NP.Nanoparticle()

p.truncated_octahedron(6,0,{'Pt':1})
p.construct_adsorption_list()
list_ads = p.get_adsorption_as_list()

site_and_generalized_coordination_number = np.zeros(p.get_total_number_of_sites())

for i,ads_site_atom_indices in enumerate(list_ads):
        site_and_generalized_coordination_number[i] = p.get_generalized_coordination_number(ads_site_atom_indices)

Resulting stoichiometry: {'Pt': 146}


In [40]:
all_generalized_coordination_number = list(p.get_generalized_coordination_numbers(list_ads).keys())

In [50]:
p.random_occupation(40)
occupation_generalized_coordination_number = np.zeros(len(all_generalized_coordination_number))
for f in p.get_indices_of_adsorbates():   
    index = all_generalized_coordination_number.index(site_and_generalized_coordination_number[f])
    occupation_generalized_coordination_number[index] += 1
occupation_generalized_coordination_number

array([0., 2., 2., 1., 2., 1., 1., 0., 3., 0., 3., 4., 1., 5., 2., 6., 2.,
       3., 0., 1., 1.])

In [52]:
occupation_generalized_coordination_number[0]*10

0.0

In [85]:
from Core.GlobalFeatureClassifier import GeneralizedCoordinationNumber
gcn_calculator = GeneralizedCoordinationNumber(p)
p.random_occupation(40)
gcn_calculator.compute_feature_vector(p)
p.get_feature_vector('GCN')

[ 19  51  68  74  81  91 108 114 124 130 135 157 188 194 196 199 203 215
 217 227 233 260 309 310 321 324 325 345 348 385 397 407 412 416 423 425
 451 466 477 500]


array([0., 1., 1., 2., 2., 4., 0., 3., 5., 1., 3., 3., 2., 4., 1., 6., 0.,
       1., 1., 0., 0.])

In [80]:
gcn_calculator.all_gcn.index(2.33)

0

In [82]:
p.random_occupation(40)
    p.get_indices_of_adsorbates()

array([ 13,  17,  19,  25,  26,  77,  92, 104, 114, 128, 131, 134, 171,
       174, 222, 234, 245, 260, 264, 280, 295, 328, 360, 370, 381, 395,
       420, 433, 440, 441, 458, 470, 479, 501, 502, 509, 550, 553, 574,
       587])